baseURL = "https://fda.netlify.com/"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Fencing Development Academy at Texas"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 by Tudor Saitoc"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = "1"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 by Tudor Saitoc"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "teacher"
name = "Team"
[[menu.footer]]
URL = "notice"
name = "notice"
[[menu.footer]]
URL = "event"
name = "event"
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
[[menu.footer]]
URL = "research"
name = "research"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "course"
name = "course"
weight = 2
[[menu.main]]
URL = "teacher"
name = "Team"
parent = "Pages"
[[menu.main]]
URL = "notice"
name = "notice"
parent = "Pages"
[[menu.main]]
URL = "event"
name = "event"
parent = "Pages"
[[menu.main]]
URL = "scholarship"
name = "scholarship"
parent = "Pages"
[[menu.main]]
URL = "research"
name = "research"
parent = "Pages"
[[menu.main]]
URL = "blog"
name = "blog"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "807 W Lynn St APT 220"
author = "Tudor Saitoc"
contact_form_action = "#"
description = "DevelopFencing"
email = "developfencing@gmail.com"
google_analitycs_id = ""
logo = "images/logoXX.png"
mobile = "631.559.6551"
social = []
top_header = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://netlify.us4.list-manage.com/subscribe/post?u=bef40eba69ab060228c9497f6&amp;id=3285400c3e"
mailchimp_form_name = "b_bef40eba69ab060228c9497f6_3285400c3e"
