baseURL = "https://fda.netlify.com/"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "FDA@TEX | Fencing Development Academy at Texas"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
name = "link"
weight = 6
[[menu.footer]]
URL = "research"
name = "research"
weight = 1
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
weight = 2
[[menu.footer]]
URL = "event"
name = "event"
weight = 3
[[menu.footer]]
URL = "notice"
name = "notice"
weight = 4
[[menu.footer]]
URL = "teacher"
name = "teacher"
weight = 5
[[menu.main]]
URL = "scholarship"
name = "scholarship"
parent = "Pages"
weight = 7
[[menu.main]]
URL = "event"
name = "event"
parent = "Pages"
weight = 5
[[menu.main]]
URL = "notice"
name = "notice"
parent = "Pages"
weight = 4
[[menu.main]]
URL = "teacher"
name = "teacher"
parent = "Pages"
weight = 3
[[menu.main]]
URL = "research"
name = "research"
parent = "Pages"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 10
[[menu.main]]
URL = "blog"
name = "blog"
weight = 9
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 8
[[menu.main]]
URL = "course"
name = "course"
weight = 6
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "807 W Lynn St APT 220"
author = "Tudor Saitoc"
contact_form_action = "#"
description = "This is meta description"
email = "tudor@saitoc.me"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = "6315596551"
top_header = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
